### ISSUE TITLE
Fix: kafka-controller-x restarts alot??

### ISSUE THREAD

**Issue by anderslaunerbaek** [jakobhviid/BigDataCourseExercises#76]

**Comment by anderslaunerbaek** [comment]
This will be solved using:

```
    controller:
      # allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge
      # resourcesPreset: "small"
      resources:
        requests:
          memory: "1024Mi"
          cpu: "750m"
        limits:
          memory: "3072Mi"
          cpu: "1.0"

```
see more on bitnami presets here: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
